name: Build and Deploy angular Front to EC2

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Clonar el repositorio
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Configurar Docker
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 3. Construir la imagen Docker
    - name: Build Docker image
      run: |
        docker build -t tourya-front:latest .

    # 4. Subir la imagen al registro de contenedores de docker hub
    - name: Push Docker image to Docker Hub
      run: |
        docker tag tourya-front:latest ${{ secrets.DOCKER_USERNAME }}/tourya-front:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/tourya-front:latest

    # 5. Desplegar en la máquina EC2
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          # Descargar la última imagen desde Docker Hub
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/tourya-front:latest
          
          # Detener y eliminar el contenedor existente (si lo hay)
          sudo docker stop tourya-front || true
          sudo docker rm tourya-front || true
          
          # Ejecutar el nuevo contenedor
          sudo docker run -d --name tourya-front -p 8080:80 \        
            ${{ secrets.DOCKER_USERNAME }}/tourya-front:latest